---
title: "Ćwiczenia #3"
output: webexercises::webexercises_default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(webexercises)
library(countdown)
```

```{r}
countdown(minutes = 3, top = 0)
```


## Zadania na zajęcia

**Ćwiczenie** 1. Zadeklaruj następującą macierz

$$
A =
 \begin{pmatrix}
3 & 1&  -2 \\
-3 & 2 & 1 \\
-2 & 6&  3 \\
 \end{pmatrix},
$$



`r hide("Rozwiązanie")`
```{r, echo = TRUE, eval = F}
A <- matrix(data = c(3, 1, -2, -3, 2, 1, -2, 6, 3), nrow = 3, byrow = T)
A
```
`r unhide()`

**Ćwiczenie** 2. Zadeklaruj następującą macierz

$$
B =
 \begin{pmatrix}
1&  2&  -2 \\
0&  2&  -1 \\
 \end{pmatrix},
$$

`r hide("Rozwiązanie")`
```{r, echo = TRUE, eval = F}
B <- matrix(data = c(1, 2, -2, 0, 2, -1), ncol = 3, byrow = T) 
B
```
`r unhide()`


**Ćwiczenie** 3. Zadeklaruj następującą macierz

$$
C =
 \begin{pmatrix}
1&  2\\
3&  4\\
 \end{pmatrix}
$$

`r hide("Rozwiązanie")`
```{r, echo = TRUE, eval = F}
C <- matrix(data = 1:4, ncol = 2, byrow = T)
C
```
`r unhide()`


