---
title: "Zajęcia -- obiekty"
output: 
  html_notebook:
    toc: yes
---

# Zajęcia 2023.10.17

## Wektory

Tworzymy ciąg liczb całkowitych od 1 do 10

```{r}
1:10
-1:-10
c(1,2,3,4,5,6,7,8,9,10) ## tworzenie wektora z funkcją c
```
Tworzę wektor składający się z wartości 1, 5, 1000

```{r}
x1 <- c(1, 5, 1000)
x1[1]
x1[2]
x1[1:2]
x1[c(1,2)]
x1[c(1,3)]
tail(x1,1) ## ostatni element
x1[length(x1)] ## funkcja length zwraca długość
```

Zastępujemy określone elementy wektor x1 innymi wartościami

```{r}
x1[1] <- 10
x2 <- x1 ## kopia x1
x1[c(1, 3)] <- c(999, -1000)
x1
```

przykłady wektoryzacji obliczen

```{r}
x1*2
sqrt(abs(x1))
```

```{r}
mean(x1)
summary(x1)
```

tworzymy wektor tekstowy

```{r}
t1 <- c("ala", "ma", "kota")
t1[2] <- 100
t1
class(t1)
```

Doklejamy do każdego elementu z wektora t1 liczbę 100

```{r}
paste(t1, 100, sep = "_")
```

Wektor logiczny

```{r}
l1 <- c(TRUE, T, FALSE, F)
l1
```

Chcę sprawdzić które elementy wektor x1 są większe od 0

```{r}
x1 > 0
```

## Macierze

## Listy

